-- --- @class GitWorktreeOperation
--
-- --- @return GitWorktreeOperation: A enum reperesenting worktree operation being performed
-- local Enum = function(tbl)
--     return setmetatable(tbl, {
--         __index = function(_, key)
--             error(string.format("%s does not exist for this enum.", key))
--         end,
--
--         __newindex = function(_, _, _)
--             error("Enums are immutable. You are not able to set new values")
--         end,
--     })
-- end
--
-- return {
--     Operation = Enum({
--         Create = "create",
--         Switch = "switch",
--         Delete = "delete",
--     }),
-- }
